### ISSUE TITLE
Integrate fastify-websockets and expose a fastify plugin 

### ISSUE THREAD

**Issue by dialexo** [graasp/graasp-websockets#2]
The idea is to separate the concerns of fastify from the websockets.

- [`WebSocketChannels`](https://github.com/graasp/graasp-websockets/blob/60e7917af88e63cc29215ea27050430bb8b3c94b/src/ws-channels.ts) should provide the broadcast, channels, and websocket server logic
- [`service-api.ts`](https://github.com/graasp/graasp-websockets/blob/60e7917af88e63cc29215ea27050430bb8b3c94b/src/service-api.ts) should wrap `WebSocketChannels`, bind with [`fastify-websocket`](https://github.com/fastify/fastify-websocket) and expose the above features through [`fastify-plugin`](https://github.com/fastify/fastify-plugin).

Hence as `fastify-websocket` is built upon [`ws`](https://github.com/websockets/ws), it makes sense that `WebSocketChannels` should provide an abstraction on top of `ws` itself directly (this could avoid state and code duplication, for instance `ws` provides direct access to connected clients).

However it seems there is a bug in the exposed type system: specifically in `fastify-websockets/index.d.ts` we can find the following declaration:
```ts
interface FastifyInstance<RawServer, RawRequest, RawReply> {
    get: RouteShorthandMethod<RawServer, RawRequest, RawReply>
    websocketServer: WebSocket.Server,
  }
```
Which is not the same as `fastify/types/instance.d.ts`:
```ts
export interface FastifyInstance<
  RawServer extends RawServerBase = RawServerDefault,
  RawRequest extends RawRequestDefaultExpression<RawServer> = RawRequestDefaultExpression<RawServer>,
  RawReply extends RawReplyDefaultExpression<RawServer> = RawReplyDefaultExpression<RawServer>,
  Logger = FastifyLoggerInstance
> {
  server: RawServer;
  prefix: string;
  version: string | undefined;
  log: Logger;
  ...
```
But the project compile just fine, even if there is this LoC which clearly type-checks against the former (it is even suggested by tsc in VSCode):
https://github.com/graasp/graasp-websockets/blob/60e7917af88e63cc29215ea27050430bb8b3c94b/src/service-api.ts#L25-L26

However at runtime, running `node dist/test/basic-fp.js` will yield the following error:
```
 this.wsServer.clients.forEach(client => {
                      ^

TypeError: Cannot read property 'clients' of undefined
    at WebSocketChannels.broadcast (/home/momochan/dev/epfl/graasp-websockets/dist/src/ws-channels.js:38:23)
    at WebSocket.<anonymous> (/home/momochan/dev/epfl/graasp-websockets/dist/src/service-api.js:44:45)
    at WebSocket.emit (events.js:326:22)
    at Receiver.receiverOnMessage (/home/momochan/dev/epfl/graasp-websockets/node_modules/ws/lib/websocket.js:825:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/home/momochan/dev/epfl/graasp-websockets/node_modules/ws/lib/receiver.js:437:14)
    at Receiver.getData (/home/momochan/dev/epfl/graasp-websockets/node_modules/ws/lib/receiver.js:367:17)
    at Receiver.startLoop (/home/momochan/dev/epfl/graasp-websockets/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/home/momochan/dev/epfl/graasp-websockets/node_modules/ws/lib/receiver.js:78:10)
    at doWrite (_stream_writable.js:403:12)
```

So clearly the compiler got confused at some point. Which means that the `ws` `Server` instance cannot be found through the `FastifyInstance` itself that is made available as plugin parameter. Even if we obtain the instance returned by registering `fastify-websockets`:
```
const wsFastify = fastify.register(fws, ...
```
This won't work. Of course it makes sense with the types, but from the documentation this means that either the ws Server is available only after finishing the top-level fastify() call and the property is added at runtime, or the `fastify` import itself should be drawn from `fastify-websockets` itself and not `fastify`. Not sure though, doesn't seem right.

### Solutions

- Find another way to access the `ws` Server instance (how?)
- Raise the level of abstraction above `fastify-websocket`, however this will duplicate state (such as connected clients) and will closely couple fastify to the websockets and channels. We may need to duplicate state anyway, as we will need to remember which client is subscribed to which channels.

**Comment by dialexo** [comment]
Update:

`fastify-websocket` does indeed perform runtime  decoration of the `fastify` instance on the JS side (`fastify-websocket/index.js`):

```js
  const wss = new WebSocket.Server(options)
  wss.on('connection', handleRouting)

  fastify.decorate('websocketServer', wss)
```
The doc (https://www.fastify.io/docs/v1.14.x/Decorators/) states that in JS, the decorator name becomes callable on the instance, i.e. `fastify.websocketServer` should indeed retrieve the Server object. Not sure what's happening here...

**Comment by dialexo** [comment]
Create own instance of ws Server and pass it to fastify websockets?

**Comment by dialexo** [comment]
await before fastify.register
