### ISSUE TITLE
Jest coverage not showing up in freshly cloned repo

### ISSUE THREAD

**Issue by dialexo** [graasp/graasp-websockets#5]
Jest coverage does not work in a freshly cloned instance:

```
 $ npm run test

> graasp-websockets@0.1.0 test /home/momochan/dev/epfl/test
> npm run build && npx jest


> graasp-websockets@0.1.0 build /home/momochan/dev/epfl/test
> tsc

 PASS  test/fastify.test.ts
  ✓ fastify validates body response instead of request on GET endpoint (34 ms)
  ✓ fastify-websocket cannot accept POST requests for websocket connections (3 ms)

 PASS  test/multi-instance.test.ts
  ✓ Message sent on a multi-instance broker is received by all instances (41 ms)

  console.log
    graasp-websockets: ejecting client undefined, timeout detected

      at src/ws-channels.ts:115:29
          at Map.forEach (<anonymous>)

  console.log
    graasp-websockets: removing channel "test" with removeIfEmpty=true: no subscribers left on this instance

      at src/ws-channels.ts:128:29
          at Map.forEach (<anonymous>)

 PASS  test/ws-channels.test.ts
  Server internal behavior
    ✓ Adding / removing a channel is registered (4 ms)
    ✓ Client connecting to server is registered and then removed on close (75 ms)
    ✓ Client sending a disconnect message is removed (12 ms)
    ✓ Client with broken connection is unregistered by heartbeat (213 ms)
    ✓ Empty channel with removeIfEmpty flag is eventually removed by heartbeat (102 ms)
    ✓ Channel with removeIfEmpty is removed when its last subscriber unsubscribes from it (12 ms)
    ✓ Client that is removed is also deleted from channel subscribers (58 ms)
    ✓ Removing a channel with subscribers removes subscription from them (12 ms)
  Client requests are handled
    ✓ Client sending an ill-formed request receives an error message (2 ms)
    ✓ Client using subscribeOnly on multiple channels only receives from last (10 ms)
    ✓ Client unsubscribing from a channel does not receive messages anymore (7 ms)
  Channel messages sent by server are received by clients
    ✓ Clients subscribed to channel '1' all receive 'msg1' (1 ms)
    ✓ Clients subscribed to channel '2' all receive 'msg2
    ✓ Clients subscribed to channel '2' all receive 'hello2' but not 'hello1' sent to channel '1' (2 ms)
    ✓ All clients receive broadcasts even if not subscribed to channels (2 ms)

----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
Test Suites: 3 passed, 3 total
Tests:       18 passed, 18 total
Snapshots:   0 total
Time:        2.329 s, estimated 3 s
Ran all test suites.
```

However the CI works just fine... https://github.com/graasp/graasp-websockets/runs/2820825971?check_suite_focus=true#step:7:51
```
> graasp-websockets@0.1.0 test:ci /home/runner/work/graasp-websockets/graasp-websockets
> npx jest --ci --colors

  console.log
    graasp-websockets: ejecting client undefined, timeout detected

      at src/ws-channels.ts:115:29
          at Map.forEach (<anonymous>)

  console.log
    graasp-websockets: removing channel "test" with removeIfEmpty=true: no subscribers left on this instance

      at src/ws-channels.ts:128:29
          at Map.forEach (<anonymous>)

 PASS  test/ws-channels.test.ts (6.869 s)
  Server internal behavior
    ✓ Adding / removing a channel is registered (6 ms)
    ✓ Client connecting to server is registered and then removed on close (96 ms)
    ✓ Client sending a disconnect message is removed (19 ms)
    ✓ Client with broken connection is unregistered by heartbeat (224 ms)
    ✓ Empty channel with removeIfEmpty flag is eventually removed by heartbeat (104 ms)
    ✓ Channel with removeIfEmpty is removed when its last subscriber unsubscribes from it (13 ms)
    ✓ Client that is removed is also deleted from channel subscribers (63 ms)
    ✓ Removing a channel with subscribers removes subscription from them (12 ms)
  Client requests are handled
    ✓ Client sending an ill-formed request receives an error message (5 ms)
    ✓ Client using subscribeOnly on multiple channels only receives from last (13 ms)
    ✓ Client unsubscribing from a channel does not receive messages anymore (12 ms)
  Channel messages sent by server are received by clients
    ✓ Clients subscribed to channel '1' all receive 'msg1' (2 ms)
    ✓ Clients subscribed to channel '2' all receive 'msg2 (1 ms)
    ✓ Clients subscribed to channel '2' all receive 'hello2' but not 'hello1' sent to channel '1' (3 ms)
    ✓ All clients receive broadcasts even if not subscribed to channels (7 ms)

 PASS  test/fastify.test.ts
  ✓ fastify validates body response instead of request on GET endpoint (39 ms)
  ✓ fastify-websocket cannot accept POST requests for websocket connections (5 ms)

 PASS  test/multi-instance.test.ts
  ✓ Message sent on a multi-instance broker is received by all instances (34 ms)

-----------------------------------|---------|----------|---------|---------|-------------------------------------------
File                               | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                         
-----------------------------------|---------|----------|---------|---------|-------------------------------------------
All files                          |   86.49 |    65.43 |      80 |   87.32 |                                           
 client/impls                      |     100 |      100 |     100 |     100 |                                           
  ajv-client-message-serializer.ts |     100 |      100 |     100 |     100 |                                           
 src                               |   85.86 |    65.43 |   81.63 |   87.05 |                                           
  config.ts                        |     100 |       75 |     100 |     100 | 16-17                                     
  multi-instance.ts                |   85.29 |       60 |    87.5 |   85.29 | 76,101-102,110,114                        
  service-api.ts                   |   75.36 |       50 |   42.86 |   78.46 | 55-56,110,122,157-159,165-167,174-176,183 
  ws-channels.ts                   |   93.41 |    74.36 |     100 |   93.33 | 105-106,146,193,226,273                   
 src/impls                         |     100 |      100 |     100 |     100 |                                           
  ajv-message-serializer.ts        |     100 |      100 |     100 |     100 |                                           
 src/interfaces                    |      75 |      100 |      50 |      60 |                                           
  message.ts                       |      75 |      100 |      50 |      60 | 96-108                                    
 src/schemas                       |     100 |      100 |     100 |     100 |                                           
  message-schema.ts                |     100 |      100 |     100 |     100 |                                           
-----------------------------------|---------|----------|---------|---------|-------------------------------------------
Test Suites: 3 passed, 3 total
Tests:       18 passed, 18 total
Snapshots:   0 total
Time:        10.788 s
Ran all test suites. 
```

Find out why coverage is not collected when the repo is freshly cloned

**Comment by dialexo** [comment]
Solution: don't clone the repo into a folder called `test`. As the repo subfolder "test" is ignored by Jest, the path name also matches the ignore directive...
